package com.alpacaflow.meditrackplatform.devices.domain.model.aggregates;

import com.alpacaflow.meditrackplatform.devices.domain.model.commands.CreateAlertCommand;
import com.alpacaflow.meditrackplatform.devices.domain.model.valueobjects.EAlertType;
import com.alpacaflow.meditrackplatform.shared.domain.model.aggregates.AuditableAbstractAggregateRoot;
import jakarta.persistence.*;
import lombok.Getter;
import org.apache.logging.log4j.util.Strings;

import java.time.LocalDateTime;

/**
 * Alert aggregate root
 * @summary
 * This aggregate root represents an alert generated by a device.
 * An alert is triggered when a measurement exceeds safe thresholds.
 * @since 1.0
 */
@Getter
@Entity
public class Alert extends AuditableAbstractAggregateRoot<Alert> {
    @Column(nullable = false)
    private Long deviceId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EAlertType alertType;

    @Column(nullable = false)
    private String message;

    @Column(nullable = false)
    private double dataRegistered;

    @Column(nullable = false)
    private LocalDateTime registeredAt;

    public Alert() {
        this.message = Strings.EMPTY;
        this.registeredAt = LocalDateTime.now();
    }

    /**
     * Create a new alert
     * @param deviceId The device ID that generated the alert
     * @param dataRegistered The measurement value that triggered the alert
     * @param measurementType The type of measurement
     */
    public Alert(Long deviceId, double dataRegistered, String measurementType) {
        this();
        this.deviceId = deviceId;
        this.dataRegistered = dataRegistered;
        this.alertType = EAlertType.DANGER;
        this.message = setMessage(measurementType);
        this.registeredAt = LocalDateTime.now();
    }

    /**
     * Create a new alert with information from the command
     * @param command The command to create the alert
     * @see CreateAlertCommand
     */
    public Alert(CreateAlertCommand command) {
        this(command.deviceId(), command.dataRegistered(), command.measurementType());
    }

    /**
     * Set the alert message based on measurement type
     * @param measurementType The type of measurement
     * @return The formatted message
     */
    private String setMessage(String measurementType) {
        return switch (measurementType.toUpperCase()) {
            case "TEMPERATURE" -> String.format("High temperature recorded: %.2f°C", dataRegistered);
            case "HEARTRATE", "HEART_RATE" -> String.format("Abnormal heart rate recorded: %.0f bpm", dataRegistered);
            case "OXYGEN" -> String.format("Low oxygen saturation recorded: %.0f%%", dataRegistered);
            case "BLOODPRESSURE", "BLOOD_PRESSURE" -> String.format("Abnormal blood pressure recorded: %.0f mmHg", dataRegistered);
            default -> "Unknown measurement type";
        };
    }
}

